language: node_js
node_js:
  - '8'
cache: yarn

install:
  - yarn global add vsce

jobs:
  include:
    - stage: deploy
      script: skip
      deploy:
        provider: script
        script: vsce publish -p $VSCE_TOKEN
        skip_cleanup: true
        on:
          tags: true
